# Generated by Django 3.1 on 2020-10-21 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_compositor_musica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estrela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tamanho', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Constelacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('estrelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contelacao', to='myapp.estrela')),
            ],
        ),
    ]
